version: 1.2
workflows:
       -  name: foobar2
          subclass: cwl
          primaryDescriptorPath: /Dockstore.cwl
          latestTagAsDefault: true
          disableDoiGeneration: true
          testParameterFiles:
              - /dockstore.cwl.json 
          authors:
              - orcid: 0000-0003-4896-1858
